/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WasteDebrisRemovalRouteImport } from './routes/waste-debris-removal'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PropertyMaintenanceRouteImport } from './routes/property-maintenance'
import { Route as PressureWashingRouteImport } from './routes/pressure-washing'
import { Route as PostConstructionCleaningRouteImport } from './routes/post-construction-cleaning'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LetsTalkRouteImport } from './routes/lets-talk'
import { Route as LandscapingRouteImport } from './routes/landscaping'
import { Route as JunkRemovalRouteImport } from './routes/junk-removal'
import { Route as FreeEstimateRouteImport } from './routes/free-estimate'
import { Route as DemolitionRouteImport } from './routes/demolition'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WasteDebrisRemovalRoute = WasteDebrisRemovalRouteImport.update({
  id: '/waste-debris-removal',
  path: '/waste-debris-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyMaintenanceRoute = PropertyMaintenanceRouteImport.update({
  id: '/property-maintenance',
  path: '/property-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureWashingRoute = PressureWashingRouteImport.update({
  id: '/pressure-washing',
  path: '/pressure-washing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostConstructionCleaningRoute =
  PostConstructionCleaningRouteImport.update({
    id: '/post-construction-cleaning',
    path: '/post-construction-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LetsTalkRoute = LetsTalkRouteImport.update({
  id: '/lets-talk',
  path: '/lets-talk',
  getParentRoute: () => rootRouteImport,
} as any)
const LandscapingRoute = LandscapingRouteImport.update({
  id: '/landscaping',
  path: '/landscaping',
  getParentRoute: () => rootRouteImport,
} as any)
const JunkRemovalRoute = JunkRemovalRouteImport.update({
  id: '/junk-removal',
  path: '/junk-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEstimateRoute = FreeEstimateRouteImport.update({
  id: '/free-estimate',
  path: '/free-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemolitionRoute = DemolitionRouteImport.update({
  id: '/demolition',
  path: '/demolition',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRoute
  '/demolition': typeof DemolitionRoute
  '/free-estimate': typeof FreeEstimateRoute
  '/junk-removal': typeof JunkRemovalRoute
  '/landscaping': typeof LandscapingRoute
  '/lets-talk': typeof LetsTalkRoute
  '/login': typeof LoginRoute
  '/our-work': typeof OurWorkRoute
  '/post-construction-cleaning': typeof PostConstructionCleaningRoute
  '/pressure-washing': typeof PressureWashingRoute
  '/property-maintenance': typeof PropertyMaintenanceRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/waste-debris-removal': typeof WasteDebrisRemovalRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRoute
  '/demolition': typeof DemolitionRoute
  '/free-estimate': typeof FreeEstimateRoute
  '/junk-removal': typeof JunkRemovalRoute
  '/landscaping': typeof LandscapingRoute
  '/lets-talk': typeof LetsTalkRoute
  '/login': typeof LoginRoute
  '/our-work': typeof OurWorkRoute
  '/post-construction-cleaning': typeof PostConstructionCleaningRoute
  '/pressure-washing': typeof PressureWashingRoute
  '/property-maintenance': typeof PropertyMaintenanceRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/waste-debris-removal': typeof WasteDebrisRemovalRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRoute
  '/demolition': typeof DemolitionRoute
  '/free-estimate': typeof FreeEstimateRoute
  '/junk-removal': typeof JunkRemovalRoute
  '/landscaping': typeof LandscapingRoute
  '/lets-talk': typeof LetsTalkRoute
  '/login': typeof LoginRoute
  '/our-work': typeof OurWorkRoute
  '/post-construction-cleaning': typeof PostConstructionCleaningRoute
  '/pressure-washing': typeof PressureWashingRoute
  '/property-maintenance': typeof PropertyMaintenanceRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/waste-debris-removal': typeof WasteDebrisRemovalRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-us'
    | '/contact'
    | '/contact-us'
    | '/dashboard'
    | '/demolition'
    | '/free-estimate'
    | '/junk-removal'
    | '/landscaping'
    | '/lets-talk'
    | '/login'
    | '/our-work'
    | '/post-construction-cleaning'
    | '/pressure-washing'
    | '/property-maintenance'
    | '/reviews'
    | '/services'
    | '/waste-debris-removal'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-us'
    | '/contact'
    | '/contact-us'
    | '/dashboard'
    | '/demolition'
    | '/free-estimate'
    | '/junk-removal'
    | '/landscaping'
    | '/lets-talk'
    | '/login'
    | '/our-work'
    | '/post-construction-cleaning'
    | '/pressure-washing'
    | '/property-maintenance'
    | '/reviews'
    | '/services'
    | '/waste-debris-removal'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-us'
    | '/contact'
    | '/contact-us'
    | '/dashboard'
    | '/demolition'
    | '/free-estimate'
    | '/junk-removal'
    | '/landscaping'
    | '/lets-talk'
    | '/login'
    | '/our-work'
    | '/post-construction-cleaning'
    | '/pressure-washing'
    | '/property-maintenance'
    | '/reviews'
    | '/services'
    | '/waste-debris-removal'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  DashboardRoute: typeof DashboardRoute
  DemolitionRoute: typeof DemolitionRoute
  FreeEstimateRoute: typeof FreeEstimateRoute
  JunkRemovalRoute: typeof JunkRemovalRoute
  LandscapingRoute: typeof LandscapingRoute
  LetsTalkRoute: typeof LetsTalkRoute
  LoginRoute: typeof LoginRoute
  OurWorkRoute: typeof OurWorkRoute
  PostConstructionCleaningRoute: typeof PostConstructionCleaningRoute
  PressureWashingRoute: typeof PressureWashingRoute
  PropertyMaintenanceRoute: typeof PropertyMaintenanceRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  WasteDebrisRemovalRoute: typeof WasteDebrisRemovalRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waste-debris-removal': {
      id: '/waste-debris-removal'
      path: '/waste-debris-removal'
      fullPath: '/waste-debris-removal'
      preLoaderRoute: typeof WasteDebrisRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-maintenance': {
      id: '/property-maintenance'
      path: '/property-maintenance'
      fullPath: '/property-maintenance'
      preLoaderRoute: typeof PropertyMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-washing': {
      id: '/pressure-washing'
      path: '/pressure-washing'
      fullPath: '/pressure-washing'
      preLoaderRoute: typeof PressureWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-construction-cleaning': {
      id: '/post-construction-cleaning'
      path: '/post-construction-cleaning'
      fullPath: '/post-construction-cleaning'
      preLoaderRoute: typeof PostConstructionCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lets-talk': {
      id: '/lets-talk'
      path: '/lets-talk'
      fullPath: '/lets-talk'
      preLoaderRoute: typeof LetsTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landscaping': {
      id: '/landscaping'
      path: '/landscaping'
      fullPath: '/landscaping'
      preLoaderRoute: typeof LandscapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junk-removal': {
      id: '/junk-removal'
      path: '/junk-removal'
      fullPath: '/junk-removal'
      preLoaderRoute: typeof JunkRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-estimate': {
      id: '/free-estimate'
      path: '/free-estimate'
      fullPath: '/free-estimate'
      preLoaderRoute: typeof FreeEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demolition': {
      id: '/demolition'
      path: '/demolition'
      fullPath: '/demolition'
      preLoaderRoute: typeof DemolitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  DashboardRoute: DashboardRoute,
  DemolitionRoute: DemolitionRoute,
  FreeEstimateRoute: FreeEstimateRoute,
  JunkRemovalRoute: JunkRemovalRoute,
  LandscapingRoute: LandscapingRoute,
  LetsTalkRoute: LetsTalkRoute,
  LoginRoute: LoginRoute,
  OurWorkRoute: OurWorkRoute,
  PostConstructionCleaningRoute: PostConstructionCleaningRoute,
  PressureWashingRoute: PressureWashingRoute,
  PropertyMaintenanceRoute: PropertyMaintenanceRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  WasteDebrisRemovalRoute: WasteDebrisRemovalRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
